
name: Compare Diff Workflow

on:
  workflow_dispatch:
    inputs:
      new_commit:
        description: "New commit SHA"
        required: true

jobs:
  compare-diff:
    runs-on: ubuntu-latest

    env:
      PREV_COMMIT: "37be3d02e5b8824b79ebf48dd73aeb5169056d29"
      GH_TOKEN: "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"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      # - name: Set up Git with GH_TOKEN
      #   run: |
      #     git config --global user.name "bubibubing"
      #     git config --global user.email "nina826120380@gmail.com"
      #     echo "//github.com/bubibubing/MBYI.git" | gh auth login --with-token

      - name: Fetch changes
        run: git fetch origin ${{ env.PREV_COMMIT }}:${{ env.PREV_COMMIT }}

      - name: Get commit messages
        run: |
          COMMIT_MESSAGES=$(git log --pretty=format:"%s" ${{ env.PREV_COMMIT }}..${{ github.event.inputs.new_commit }})
          echo "Commit messages between ${{ env.PREV_COMMIT }} and ${{ github.event.inputs.new_commit }}:"
          echo "$COMMIT_MESSAGES"

      - name: Set new commit as prev_commit
        run: echo "PREV_COMMIT=${{ github.event.inputs.new_commit }}" >> $GITHUB_ENV
